/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package SegundoParcial;
import java.util.ArrayList;


/**
 *
 * @author damia
 */
public class DiagramaVen extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DiagramaVen.class.getName());

    /**
     * Creates new form DiagramaVen
     */
    public DiagramaVen() {
        initComponents();
        this.setTitle("DIAGRAMA DE VEN");
        this.setLocationRelativeTo(null);
    }
    
    public void DiagramaEntero (){
        
        String DatosTotales = (EntradaTotal.getText());
        String[] ContTotal = DatosTotales.split("\\n");
        int Total[] = new int[ContTotal.length];

        String DatosA = (EntradaA.getText());
        String[] ContA = DatosA.split("\\n");
        int TotalA[] = new int[ContA.length];

        String DatosB = (EntradaB.getText());
        String[] ContB = DatosB.split("\\n");
        int TotalB[] = new int[ContB.length];

        for (int i = 0; i < ContA.length; i++) {
            TotalA[i] = Integer.parseInt(ContA[i].trim());
        }
        
        for (int i = 0; i < ContB.length; i++) {
            TotalB[i] = Integer.parseInt(ContB[i].trim());
        }

        for (int i = 0; i < ContTotal.length; i++) {
            Total[i] = Integer.parseInt(ContTotal[i].trim());
        }
        ArrayList<Integer> ListaAB = new ArrayList<>();

        for (int i = 0; i < TotalA.length; i++) {
            for (int j = 0; j < TotalB.length; j++) {
                if (TotalA[i] == TotalB[j]) {
                    SalidaAB.append(TotalA[i] + "\n");
                    ListaAB.add(TotalA[i]);
                }
            }
        }

        ArrayList<Integer> ListaA = new ArrayList<>();

        for (int i = 0; i < TotalA.length; i++) {
            boolean Bandera = false;
            for (int j = 0; j < ListaAB.size(); j++) {
                if (ListaAB.get(j) == TotalA[i]) {
                    Bandera = true;
                    break;
                }
            }
            if (Bandera == false) {
                SalidaA.append(TotalA[i] + "\n");
                ListaA.add(TotalA[i]);
            }
        }

        ArrayList<Integer> ListaB = new ArrayList<>();

        for (int i = 0; i < TotalB.length; i++) {
            boolean Bandera = false;
            for (int j = 0; j < ListaAB.size(); j++) {
                if (ListaAB.get(j) == TotalB[i]) {
                    Bandera = true;
                    break;
                }
            }
            if (Bandera == false) {
                SalidaB.append(TotalB[i] + "\n");
                ListaB.add(TotalB[i]);
            }
        }
        //aqui se compara si todos los datos ingresados estan en A o B 
        // en caso de que no esten se imprimen los numeros afuera de los circulos
        //De igual manera se crea una lista para despues hacer las operaciones 
        ArrayList<Integer> ListaAfuera = new ArrayList<>();
        for (int j = 0; j < Total.length; j++) {
            boolean Bandera2 = false;

            for (int i = 0; i < TotalA.length; i++) {
                boolean Bandera1 = false;
                if (Total[j] == TotalA[i]) {
                    Bandera2 = true;
                    break;
                }

            }
            if (Bandera2 == false) {
                boolean Bandera2_1 = false;
                for (int i = 0; i < TotalB.length; i++) {
                    if (Total[j] == TotalB[i]) {
                        Bandera2_1 = true;
                    }
                }
                if (Bandera2_1 == false) {
                    SalidaTotal.append(Total[j] + "\n");
                    ListaAfuera.add(Total[j]);
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        SalidaAB = new javax.swing.JTextArea();
        SalidaB = new javax.swing.JTextArea();
        SalidaTotal = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        SalidaA = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        EntradaB = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        EntradaTotal = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        EntradaA = new javax.swing.JTextArea();
        BtnDecimal = new javax.swing.JButton();
        BtnEntero = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SalidaAB.setColumns(20);
        SalidaAB.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        SalidaAB.setRows(5);
        jPanel1.add(SalidaAB, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 250, 50, -1));

        SalidaB.setColumns(20);
        SalidaB.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        SalidaB.setRows(5);
        jPanel1.add(SalidaB, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 250, 50, -1));

        SalidaTotal.setColumns(20);
        SalidaTotal.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        SalidaTotal.setRows(5);
        jPanel1.add(SalidaTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 410, 50, -1));

        jLabel2.setBackground(new java.awt.Color(204, 255, 255));
        jLabel2.setFont(new java.awt.Font("Elephant", 0, 36)); // NOI18N
        jLabel2.setText("DIAGRAMA DE VENN");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(353, 6, -1, -1));

        SalidaA.setColumns(20);
        SalidaA.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        SalidaA.setRows(5);
        jPanel1.add(SalidaA, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 250, 50, -1));

        jLabel3.setText("INGRESA TUS DATOS");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 151, -1, -1));

        jLabel4.setText("INGRESA TUS DATOS A");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(981, 307, -1, -1));

        jLabel5.setText("INGRESA TUS DATOS B");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(977, 457, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Tabla.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 63, 921, 527));

        EntradaB.setColumns(20);
        EntradaB.setRows(5);
        EntradaB.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        EntradaB.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(EntradaB);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(933, 479, 226, 104));

        EntradaTotal.setColumns(20);
        EntradaTotal.setRows(5);
        EntradaTotal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        EntradaTotal.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jScrollPane2.setViewportView(EntradaTotal);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(933, 173, 226, 122));

        EntradaA.setColumns(20);
        EntradaA.setRows(5);
        EntradaA.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        EntradaA.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jScrollPane3.setViewportView(EntradaA);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(933, 329, 226, 116));

        BtnDecimal.setText("DECIMAL");
        jPanel1.add(BtnDecimal, new org.netbeans.lib.awtextra.AbsoluteConstraints(933, 601, -1, -1));

        BtnEntero.setText("ENTEROS");
        BtnEntero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEnteroActionPerformed(evt);
            }
        });
        jPanel1.add(BtnEntero, new org.netbeans.lib.awtextra.AbsoluteConstraints(1079, 601, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 823, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnEnteroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEnteroActionPerformed
        DiagramaEntero();
    }//GEN-LAST:event_BtnEnteroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new DiagramaVen().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnDecimal;
    private javax.swing.JButton BtnEntero;
    private javax.swing.JTextArea EntradaA;
    private javax.swing.JTextArea EntradaB;
    private javax.swing.JTextArea EntradaTotal;
    private javax.swing.JTextArea SalidaA;
    private javax.swing.JTextArea SalidaAB;
    private javax.swing.JTextArea SalidaB;
    private javax.swing.JTextArea SalidaTotal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
