/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package SegundoParcial;
import javax.swing.DefaultListModel;

/**
 *
 * @author damia
 */
public class DiagramaVen extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DiagramaVen.class.getName());

    /**
     * Creates new form DiagramaVen
     */
    public DiagramaVen() {
        initComponents();
        this.setTitle("DIAGRAMA DE VEN");
        this.setLocationRelativeTo(null);
    }
    
    public void DiagramaEntero (){
        DefaultListModel ModeloAB = new DefaultListModel();
        DefaultListModel ModeloA = new DefaultListModel();
        DefaultListModel ModeloB = new DefaultListModel();
        
        String DatosTotales = (EntradaTotal.getText());
        String[] ContTotal = DatosTotales.split("\\n");
        int Total[] = new int [ContTotal.length];
        
        String DatosA = (EntradaA.getText());
        String[] ContA = DatosA.split("\\n");
        int TotalA[] = new int [ContA.length];
        
        String DatosB = (EntradaB.getText());
        String[] ContB = DatosB.split("\\n");
        int TotalB[] = new int [ContB.length];
        
        
        for (int i = 0; i < ContA.length; i++) {    
            TotalA[i] = Integer.parseInt(ContA[i].trim());
            
        }
               
        for (int i = 0; i < ContB.length; i++) {
            TotalB[i] = Integer.parseInt(ContB[i].trim());
            
        }
        
        for (int i = 0; i < ContTotal.length; i++) {
            Total[i] = Integer.parseInt(ContTotal[i].trim());
        }
        
        for (int i = 0; i < TotalA.length; i++) {
            for (int j = 0; j < TotalB.length; j++) {
                if (TotalA[i] == TotalB[j]){
                   ModeloAB.addElement(TotalA[i]+ "");                  
                }
            }
        }
        for (int i = 0; i <TotalA.length; i++) {
            if();
            
        }
        SalidaAB.setModel(ModeloAB);
        SalidaA.setModel(ModeloA);
        SalidaB.setModel(ModeloB);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        SalidaB = new javax.swing.JList<>();
        jScrollPane5 = new javax.swing.JScrollPane();
        SalidaA = new javax.swing.JList<>();
        jScrollPane6 = new javax.swing.JScrollPane();
        SalidaAB = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        Afuera = new javax.swing.JList<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        EntradaB = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        EntradaTotal = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        EntradaA = new javax.swing.JTextArea();
        BtnDecimal = new javax.swing.JButton();
        BtnEntero = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SalidaB.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jScrollPane4.setViewportView(SalidaB);

        jPanel1.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 250, 60, 150));

        SalidaA.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jScrollPane5.setViewportView(SalidaA);

        jPanel1.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 250, 60, 170));

        SalidaAB.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jScrollPane6.setViewportView(SalidaAB);

        jPanel1.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 250, 70, 150));

        jLabel2.setBackground(new java.awt.Color(204, 255, 255));
        jLabel2.setFont(new java.awt.Font("Elephant", 0, 36)); // NOI18N
        jLabel2.setText("DIAGRAMA DE VEN");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(353, 6, -1, -1));

        jLabel3.setText("INGRESA TUS DATOS");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 151, -1, -1));

        jLabel4.setText("INGRESA TUS DATOS A");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(981, 307, -1, -1));

        jScrollPane7.setViewportView(Afuera);

        jPanel1.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 390, 50, -1));

        jLabel5.setText("INGRESA TUS DATOS B");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(977, 457, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Tabla.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 63, 921, 527));

        EntradaB.setColumns(20);
        EntradaB.setRows(5);
        EntradaB.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        EntradaB.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(EntradaB);
        EntradaB.getAccessibleContext().setAccessibleParent(jScrollPane3);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(933, 479, 226, 104));

        EntradaTotal.setColumns(20);
        EntradaTotal.setRows(5);
        EntradaTotal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        EntradaTotal.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jScrollPane2.setViewportView(EntradaTotal);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(933, 173, 226, 122));

        EntradaA.setColumns(20);
        EntradaA.setRows(5);
        EntradaA.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        EntradaA.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jScrollPane3.setViewportView(EntradaA);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(933, 329, 226, 116));

        BtnDecimal.setText("DECIMAL");
        jPanel1.add(BtnDecimal, new org.netbeans.lib.awtextra.AbsoluteConstraints(933, 601, -1, -1));

        BtnEntero.setText("ENTEROS");
        BtnEntero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEnteroActionPerformed(evt);
            }
        });
        jPanel1.add(BtnEntero, new org.netbeans.lib.awtextra.AbsoluteConstraints(1079, 601, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 737, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnEnteroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEnteroActionPerformed
        DiagramaEntero();
    }//GEN-LAST:event_BtnEnteroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new DiagramaVen().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> Afuera;
    private javax.swing.JButton BtnDecimal;
    private javax.swing.JButton BtnEntero;
    private javax.swing.JTextArea EntradaA;
    private javax.swing.JTextArea EntradaB;
    private javax.swing.JTextArea EntradaTotal;
    private javax.swing.JList<String> SalidaA;
    private javax.swing.JList<String> SalidaAB;
    private javax.swing.JList<String> SalidaB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    // End of variables declaration//GEN-END:variables
}
